-- ============================================
-- CinePick Seed Data (수정본 v2)
-- cast → cast_members 로 변경
-- ============================================

INSERT INTO movies (title, original_title, poster, backdrop, genre, mood, duration, rating, description, director, cast_members, release_year, language, country, age_rating, ott_platform, trending_score, is_new) VALUES

('인터스텔라', 'Interstellar',
 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIe.jpg',
 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
 ARRAY['SF', '드라마', '어드벤처'],
 ARRAY['감동적인', '서사적인', '생각하게하는'],
 169, 8.7,
 '지구의 미래가 위태로워지자, 전직 NASA 파일럿 쿠퍼는 인류의 새로운 보금자리를 찾기 위한 우주 탐험대에 합류한다.',
 '크리스토퍼 놀란',
 ARRAY['매튜 맥커너히', '앤 해서웨이', '제시카 차스테인'],
 2014, 'en', '미국', '12세', ARRAY['Netflix', 'Watcha'], 95, FALSE),

('기생충', 'Parasite',
 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
 ARRAY['드라마', '스릴러', '블랙코미디'],
 ARRAY['긴장감있는', '생각하게하는', '어두운'],
 132, 8.5,
 '전원 백수인 기택 가족. 장남 기우가 명문대 과외 선생으로 위장 취업하면서 시작되는 박 사장네와의 만남.',
 '봉준호',
 ARRAY['송강호', '이선균', '조여정', '최우식'],
 2019, 'ko', '한국', '15세', ARRAY['Watcha', 'Wavve'], 99, FALSE),

('어벤져스: 엔드게임', 'Avengers: Endgame',
 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
 ARRAY['액션', 'SF', '어드벤처'],
 ARRAY['흥미진진한', '서사적인', '활기찬'],
 181, 8.4,
 '타노스의 핑거스냅으로 절반의 우주가 사라진 후 5년, 남겨진 어벤져스가 모든 것을 되돌리기 위한 마지막 작전을 펼친다.',
 '루소 형제',
 ARRAY['로버트 다우니 주니어', '크리스 에반스', '마크 러팔로'],
 2019, 'en', '미국', '12세', ARRAY['Disney+'], 88, FALSE),

('존 윅', 'John Wick',
 'https://image.tmdb.org/t/p/w500/fZPSd91llGcTO8PKUE2QpqHOMyT.jpg',
 'https://image.tmdb.org/t/p/original/umC04Cozevu8nn3ZTIU9rNyfXSY.jpg',
 ARRAY['액션', '스릴러'],
 ARRAY['흥미진진한', '긴장감있는', '활기찬'],
 101, 7.4,
 '은퇴한 최고의 킬러 존 윅. 사랑하는 강아지를 잃은 후 다시 지하 세계로 돌아와 복수를 시작한다.',
 '채드 스타헬스키',
 ARRAY['키아누 리브스', '마이클 냐크비스트', '알피 앨런'],
 2014, 'en', '미국', '18세', ARRAY['Netflix', 'Watcha'], 75, FALSE),

('콜 미 바이 유어 네임', 'Call Me by Your Name',
 'https://image.tmdb.org/t/p/w500/nagl3ps1bGGh2M0NqNVZhp8dRRX.jpg',
 'https://image.tmdb.org/t/p/original/6nMdzGTICZBBqzEdstgmRVJHoMd.jpg',
 ARRAY['로맨스', '드라마'],
 ARRAY['감동적인', '로맨틱한', '감성적인'],
 132, 7.9,
 '1983년 이탈리아 여름, 17살 엘리오와 24살 올리버의 열여섯 번의 만남과 사랑.',
 '루카 구아다니노',
 ARRAY['티모시 샬라메', '아미 해머'],
 2017, 'en', '이탈리아', '18세', ARRAY['Watcha', 'Netflix'], 65, FALSE),

('라라랜드', 'La La Land',
 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
 'https://image.tmdb.org/t/p/original/nadTlnTE6DdCPsNGDlLnGsqWl8b.jpg',
 ARRAY['로맨스', '뮤지컬', '드라마'],
 ARRAY['로맨틱한', '감동적인', '감성적인'],
 128, 8.0,
 '재즈 피아니스트와 배우 지망생의 꿈과 사랑, 그리고 이별에 관한 이야기.',
 '데이미언 셔젤',
 ARRAY['라이언 고슬링', '엠마 스톤'],
 2016, 'en', '미국', '12세', ARRAY['Netflix', 'Watcha', 'Wavve'], 80, FALSE),

('겟 아웃', 'Get Out',
 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
 'https://image.tmdb.org/t/p/original/3ri8xZ2TrKiV6rLtSSTnDEKtpme.jpg',
 ARRAY['공포', '스릴러', '미스터리'],
 ARRAY['긴장감있는', '어두운', '소름돋는'],
 104, 7.7,
 '흑인 청년 크리스가 백인 여자친구 로즈의 가족을 만나기 위해 방문하면서 벌어지는 소름 끼치는 이야기.',
 '조던 필',
 ARRAY['다니엘 칼루야', '앨리슨 윌리엄스'],
 2017, 'en', '미국', '15세', ARRAY['Watcha', 'Wavve'], 70, FALSE),

('극한직업', 'Extreme Job',
 'https://image.tmdb.org/t/p/w500/wJ7mVTbMFuJf3PKOL8MWi7WJUiE.jpg',
 'https://image.tmdb.org/t/p/original/9eABlMHcFr8uVdJxfH6r9LOIq7k.jpg',
 ARRAY['코미디', '액션', '범죄'],
 ARRAY['유쾌한', '활기찬', '웃긴'],
 111, 7.4,
 '마약반 형사들이 범죄 조직 감시를 위해 치킨집을 인수했다가 치킨이 대박나는 코믹 범죄 액션.',
 '이병헌',
 ARRAY['류승룡', '이하늬', '진선규', '이동휘'],
 2019, 'ko', '한국', '15세', ARRAY['Netflix', 'Watcha', 'Wavve'], 82, FALSE),

('기묘한 이야기 시즌 4', 'Stranger Things Season 4',
 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
 ARRAY['SF', '공포', '드라마', '어드벤처'],
 ARRAY['긴장감있는', '흥미진진한', '소름돋는'],
 77, 8.5,
 '호킨스에 새로운 위협이 등장하고 멀리 떨어진 아이들이 다시 뭉쳐야 한다.',
 '더퍼 형제',
 ARRAY['밀리 바비 브라운', '핀 울프하드', '게이튼 마타라초'],
 2022, 'en', '미국', '15세', ARRAY['Netflix'], 97, FALSE),

('스파이더맨: 어크로스 더 유니버스', 'Spider-Man: Across the Spider-Verse',
 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
 ARRAY['애니메이션', '액션', '어드벤처', 'SF'],
 ARRAY['흥미진진한', '활기찬', '서사적인'],
 140, 8.7,
 '마일스 모랄레스가 멀티버스를 넘나들며 새로운 스파이더 소사이어티와 맞닥뜨리는 이야기.',
 '호아킨 도스 산토스',
 ARRAY['샤메익 무어', '헤일리 스테인펠드', '오스카 아이삭'],
 2023, 'en', '미국', '12세', ARRAY['Netflix'], 96, TRUE),

('오펜하이머', 'Oppenheimer',
 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
 ARRAY['전기', '드라마', '역사', '스릴러'],
 ARRAY['생각하게하는', '서사적인', '긴장감있는'],
 180, 8.5,
 '원자폭탄의 아버지 J. 로버트 오펜하이머의 이야기와 그가 세상을 바꾼 발명에 대한 대가를 치르는 과정.',
 '크리스토퍼 놀란',
 ARRAY['킬리언 머피', '에밀리 블런트', '맷 데이먼', '로버트 다우니 주니어'],
 2023, 'en', '미국', '15세', ARRAY['Watcha', 'Wavve'], 94, TRUE),

('바비', 'Barbie',
 'https://image.tmdb.org/t/p/w500/iuFNMS8vlzmfa9gHuBj5A2HIb4Z.jpg',
 'https://image.tmdb.org/t/p/original/nHf61UzkfFno5X1ofIjWpbVPdfN.jpg',
 ARRAY['코미디', '판타지', '어드벤처'],
 ARRAY['유쾌한', '활기찬', '웃긴'],
 114, 7.0,
 '완벽한 바비랜드에서 살던 바비가 현실 세계로 나오면서 겪는 모험과 자아 발견의 이야기.',
 '그레타 거윅',
 ARRAY['마고 로비', '라이언 고슬링', '케이트 맥키넌'],
 2023, 'en', '미국', '12세', ARRAY['Watcha'], 91, TRUE),

('더 베어', 'The Bear',
 'https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
 'https://image.tmdb.org/t/p/original/30YnfZdMNIV7noWLdvmcJS0bZHn.jpg',
 ARRAY['드라마', '코미디'],
 ARRAY['긴장감있는', '감동적인', '생각하게하는'],
 30, 8.6,
 '파인 다이닝 세계에서 일하던 셰프 카르미가 가족 샌드위치 가게를 물려받으면서 벌어지는 이야기.',
 '크리스토퍼 스토러',
 ARRAY['제레미 앨런 화이트', '에본 모스-배크락', '아요 에데비리'],
 2022, 'en', '미국', '15세', ARRAY['Disney+'], 93, TRUE),

('도적: 칼의 소리', 'The Bequeathed',
 'https://image.tmdb.org/t/p/w500/zMhKOaZjSAIyHfhiRLU5RslyVNv.jpg',
 'https://image.tmdb.org/t/p/original/xkHIcxPfGYFQUkMqMtFUEOQaY9.jpg',
 ARRAY['스릴러', '미스터리', '범죄'],
 ARRAY['긴장감있는', '어두운', '소름돋는'],
 50, 7.2,
 '갑자기 산속 묘지를 상속받은 여자와 그 주변에서 벌어지는 연쇄 살인 사건을 다룬 미스터리 스릴러.',
 '류용재',
 ARRAY['김현주', '류경수'],
 2024, 'ko', '한국', '15세', ARRAY['Netflix'], 85, TRUE),

('눈물의 여왕', 'Queen of Tears',
 'https://image.tmdb.org/t/p/w500/q2c0XjHRGbzIWhWg4TFwzPSbwKe.jpg',
 'https://image.tmdb.org/t/p/original/jPsLqiYGSofU4jTsItowQ6NbdjU.jpg',
 ARRAY['로맨스', '드라마'],
 ARRAY['감동적인', '로맨틱한', '감성적인'],
 70, 8.9,
 '결혼 3년 차에 이혼 위기를 맞은 재벌가 상속녀와 평범한 남편이 다시 사랑에 빠지는 이야기.',
 '김희원',
 ARRAY['김지원', '김수현'],
 2024, 'ko', '한국', '15세', ARRAY['Netflix'], 99, TRUE);
